### ISSUE TITLE
Android transfer integration fail

### ISSUE THREAD

**Issue by user04392** [eu-digital-identity-wallet/eudi-lib-android-iso18013-data-transfer#21]
I cloned the project and built it but I encountered a few issues: 
implementation "eu.europa.ec.eudi:eudi-lib-android-wallet-core:0.9.2-SNAPSHOT" failed to be resolved and it seems like I got some missing packages (including but not limited to com.android.identity).

**Comment by mviennas** [comment]
> I cloned the project and built it but I encountered a few issues: implementation "eu.europa.ec.eudi:eudi-lib-android-wallet-core:0.9.2-SNAPSHOT" failed to be resolved and it seems like I got some missing packages (including but not limited to com.android.identity).

This is how to load snapshots dependencies: https://github.com/eu-digital-identity-wallet/eudi-lib-android-wallet-core?tab=readme-ov-file#dependencies
We will publish not snapshot releases soon.

**Comment by mgiakkou** [comment]
Dear user04392,

We consider this closed, as the readme provided above explains how to proceed with the requested implementation. If not please reopen and provide further info.

Thank you,
Michalis.
